linux-toradex_4.1-2.0.x: imx, update to toradex bsp 2.7.4
Update the kernel for a fslc-imx 4.1-2.0.x based kernel for Apalis/Colibri iMX6
and Colibri iMX7.
This replaces the linux-toradex_3.14.52 and linux-toradex_4.1.15 kernels, thus
remove the recipes and their related files.

Add a superset of the machine specific defconfigs in the kernel tree as the
defconfig.

The following changes on top of fslc "Merge tag 'v4.1.39' into 4.1-2.0.x-imx":
- Patches for bsp 2.7.3 as listed below
- Merge to upstream patchlevel fslc/4.1-2.0.x-imx @ 4.1.44
- Patches for bsp 2.7.4 as listed below
- Added initial support Colibri iMX6ULL and Colibri iMX7 Dual 1GB (eMMC)

without the machine specific device-trees or defconfigs commits.:

with bsp 2.7.4
* b893ccb toradex defconfigs: synchronize with defconfigs in oe
* 3e11eb1 colibri_imx7_defconfig: add atmel-mxt-ts as a module
* f5f2907 ARM: dts: imx7-colibri: add atmel mxt multitouch controller
* e747c0e ARM: dts: colibri-imx7: add new gpio hog grp
* 269dba3 colibri_imx6_defconfig: add atmel-mxt-ts as a module
* b9aae76 ARM: dts: imx6dl-colibri: add atmel mxt multitouch controller
* de3fd44 apalis_imx6_defconfig: add atmel-mxt-ts as a module
* 98b9c18 ARM: dts: imx6qdl-apalis: add atmel mxt multitouch controller
* bce5146 ARM: imx: clk: enable OCOTP clock by default
* d96c255 imx6ull.dtsi: include all needed definitions
* c8f0033 mtd: gpmi: fsl,legacy-bch-geometry independent of nand-on-flash-bbt
* 7b02a99 imx: Fix 'Expose SoC unique ID' for newer i.MX6
* 4e35498 imx6dl-colibri-eval-v3: fix weim node
* 090138a regulator: pfuze100: Apalis iMX6: Fix poweroff does not release POWER_ENABLE_MOCI
* c4d5e86 apalis_imx6: update defconfig for wifi
* 837a89e ip6_offload: fix compiler warning
* 4105f39 of: fdt: fix compiler warning
* 4b20a89 mtd: blkdevs: fix switch-bool compilation warning
* c595a9e mtd: fsl-quadspi: fix macro collision problems with READ/WRITE"
* 6fe6616 Revert "mtd: fsl-quadspi: fix macro collision problems with READ/WRITE"

with bsp 2.7.3
* 3f68dc7 busfreq-imx: only use existing global variables
* 22eb8a9 Revert "cpufreq: imx7: fix undefined reference to arm_reg and soc_reg"
* 38524d7 Documentation: fix imx7d pinctrl dse config bits
* 71d7b33 imx7d-colibri: limit to 800 mhz and 1 ghz operating points
* b339205 imx7s: add mandatory 800 mhz operating point
* 22db6be video: fbdev: mxsfb: allow setting display timings via kernel command line
* a6563bd cpufreq: imx7: fix undefined reference to arm_reg and soc_reg
* 9262956 dts: imx7d: move operating points to i.MX 7Dual device tree
* 50e26af mxc_ipuv3_fb: Use the mode_string from command line as is
* d826eb4 ov5640_mipi: Revert the hack
* a5c56b9 ARM: dts: imx6qdl-apalis-ixora: Enable ADV7280 decoder on Ixora
* b8e5d21a tty: serial: imx: Add support for enabling RS485 via device tree
* a8e0d43 ARM: imx: spare the first 16KiB of OCRAM_S for Cortex-M4
* a2130af sgtl5000: improve switch on vag power for line_in -> output
* b48a96a ARM: dts: colibri imx6: configure an external sgtl5000 vddd source
* d21fcda ARM: dts: apalis imx6: configure an external sgtl5000 vddd source
* 40fbb01 ARM: dts: colibri imx6: increase sgtl5000 lrclk drive strenght
* 87f6630 ASoC: sgtl5000: Allow LRCLK pad drive strength to be changed
* 1a3c9b3 ASoC: sgtl5000: add headphone and LINEOUT mute controls
* 8929d0a sgtl5000: add Lineout volume control
* 81fba3f ASoC: sgtl5000: Do not disable regulators in SND_SOC_BIAS_OFF
* 66a04e9 ASoC: sgtl5000: Disable internal PLL early
* 85436af ASoC: sgtl5000: Initialize CHIP_ANA_POWER to power-on defaults
* 51bc42e ASoC: sgtl5000: Write all default registers
* 4523526 ASoC: sgtl5000: Fix regulator support
* 4859c2e90 ASoC: sgtl5000: Remove misleading comment
* abbdc0a ASoC: sgtl5000: fix VAG power up timing
* 198628d ASoC: sgtl5000: fix error message output for MicBias voltage
* 912e038 ASoC: sgtl5000: Replace direct snd_soc_codec dapm field access
* ae56e9d ASoC: sgtl5000: Calculate Lineout Channel Output Level
* 3db63e2 ASoC: sgtl5000: Use specific variable for lo_vag
* f972815 net: can: flexcan: Fix wakeup on CAN from suspend issue
* b6798bb iio: adc: remove event advertisment
* 7a751b2 iio: adc: support IIO_CHAN_INFO_SCALE
* 051ee1a1 apalis-imx6: use stopmode for poweroff
* 8949147 pm-imx6.c: fix power off by stop mode
* 29ff238 colibri-imx6: use stopmode for poweroff
* 94a53ed net: fec: don't transfer ownership until descriptor write is complete
* c15a4c3 rtc: ds1307: support m41t0 variant
* 3e3ea9b sgtl5000: switch on vag power for line_in -> output
* 091594e iio: adc: fix remove
* 4bac3c9 mmc: sdio: add forward declaration for struct mmc_host
* a86db1f ARM: imx: mu: let Cortex-M4 know about A7 state
* 98adbba ARM: imx: clk: do not force clock frequency of M4
* 9e05354 ARM: imx: busfreq: do not force high frequency during suspend
* 70f901b ARM: imx: busfreq: initialize M4 frequency depending boot state
* 3e92301 ARM: imx: busfreq: request bus frequency depending on M4 clock
* 0666dae arm: dts: imx7: specify Cortex-M4 clock
* c663470 mmc: sdhci-esdhc-imx: make sure runtime PM is suspended in system suspend
* 2df675a mtd: gpmi: make sure runtime PM is suspended in system suspend
* ebf4565 video: fbdev: mxsfb: make sure runtime PM is suspended in system suspend
* a2ccbd2 net: fec: make sure runtime PM is suspended in system suspend
* 5ced941 imx_thermal.c: set trip point depending on temp grade
* 9090b5b imx: Expose SoC unique ID
* 8a098f2 drivers: soc: Add new sysfs attribute to expose SoC unique ID
* 36df4e2 arm: dts: imx7: specify keypad port clock
* 7b51b63 ARM: imx7d: clk: add root clock for keypad port
* 506993e rpmsg: use _debug variants for print_hex_dump
* 5aba75e rpmsg: imx: do not push data when no reader is available
* cade8f64 hexdump: do not print debug dumps for !CONFIG_DEBUG
* 1db9a16 ARM: imx: define buffer count per VirtIO queue
* 4cfa939 gpio: mxc: clear interrupt mask/status optionally
* 25b9f89 ARM: imx: remove 'unused' warning
* 257fabb tty: serial: imx: disable DCD and RI interrupts
* c784a4d imx6qdl.dtsi: include bindings gpio.h
* 735d4f8 video: mxc: ldb: Add support for LVDS configuration via kernel boot arguments
* 558d378 colibri_imx6:Add MCP2515 SPI CAN controller to DT
* 7df8a0f media: Add support for ADV7280 decoder driver
* 358a46a mxc_v4l2_capture: Change error message to print on debug
* 80aae0b mxc_v4l2_capture: Allow clock setting for de-interlaced video input
* 0d85191 tty: serial: imx: disable DCD and RI interrupts
* 8ddc702 PCI: Apalis GEN1 forcing quirk
* 826486c PCI: imx6: fix PCIe EP device self-initialisation
* e00c546 process.c: if power off fails, do at least a halt
* be63e27 Input: sentelic - use "static inline" instead of "inline"
* b28f212 mxc_v4l2_capture.c: make error messages unique
* d7357aa ipu_csi_enc.c: fix debug print
* 4e1e8d2 max9526.c: move pinctrl after i2c detect
* 638f43c adv7180.c: convert debug output to dev_dbg
* 67c0d5a2 dtb, i2c-imx.txt: fix typos
* 1ce23b6 mxc_v4l2_capture: match ipu/csi/mipi instead of only ipu/csi
* c5954c2 max9526: add initial MXC camera sensor code
* df76b16 adv7180.c: initial working adv7180 settings
* 518d4ee mxc_v4l2_capture: let the camera driver set mipi/parallel
* 62785df pci-imx6: fix reboot bug
* d2e0de0 mxc_hdmi.c: fix boot hang
* cec9878 extcon: usb-gpio: increase debounce time
* 1fe0cf4 mxc_lcdif.c: fix comment
* 912f823 mxc_v4l2_capture: add mxc_camera_common_lock/unlock, fix device name
* 502376a MXC_CSI_CAMERA: select VIDEOBUF2_DMA_CONTIG
* 691204a clk-imx6q.c: set eth phy clock dependent on RMII/RGMII
* bea0575 mach-imx6q.c: handle RESET_MOCI when PCIe is disabled
* 78d5ad8 mxc_hdmi.c: remove compiler warning
* 2d67c55 mxc_hdmi: fix detect disconnect case
* b34325c OmniVision ov5640 MIPI-CSI2 camera support
* b548028 i2c-imx: add gpio recovery functionality
* fc0d0a2 pcie-imx6: improve reset function for reseting EP
* 557f0276 pcie-imx6: add reset function for reseting downstream EP
* b0e8865 mach-imx6q.c: fix typo in error msg
* 0bcaad8 mxc_vdacif.c: add second parallel output used for VDAC
* f069491 pci-imx6.c: add config option to force GEN1 speed
* e4d913a iio:stmpe-adc.c: Switch to new event config interface
* af6cf45 vgaarb.c: demote pr_err about vga device to pr_debug
* 4e6509c mxc_lcdif.c: add additonal LCD timings
* 849f2e7 pci-imx6.c: remove compiler warning
* 85aff64 mxc_lcdif.c: EDT-WVGA: fix pixelclk polarity
* f6620779 mxc_hdmi: skip unnecessary mxc_hdmi_setup calls
* c73cb81 sync.h: synchronization framework needs this header
* d39b4cf arm: imx6: fix pcie by disabling rc/ep test mode
* 7435612 stmpe-adc: add temperature channel
* 6f88e1d stmpe-adc: add device tree bindings
* 6b542ac iio: adc: add STMPE ADC driver using IIO framework
* d5c4b1b mfd: stmpe: add ADC block resources
* 3b99e8c mach-types: add the apalis-imx6 machine
* 6a315fa lcd: Add WVGA timings for the EDT 7.0" panel
* 6ff9133 mxc_spdif.c: set the validity bit to 'valid'
* 25c2bbc eMMC: Don't initialize partitions on RPMB flagged areas.
* d2aa5b3 tc358743_h2c: add devicetree support
* 97662d8 TC358743 Kconfig dependency update
* e966a0b tc358743_h2c: fill in sample edid data from Asus monitor
* fa98ab8 tc358743_h2c: fix compiler warnings
* 1ae41be tc358743_h2c: cleanup spacing
* cb8232e add tc358743_h2c driver
* 3bb87f2 sdhci: print opcode/retries on timeout error
* a26957b ov5640_mipi: software reset does not affect i2c address
* f157011 ipu_common: ipu_free_irq, do nothing if not owner
* 916ed1f ipu_csi_enc: improve error message
* 439ea46 ipu_prp_enc: improve error message
* cd35b25 ov5642: fix csi/ipu check for imx6dl
* 388605f ov5640_mipi: fix csi/ipu check for imx6dl
* 07bd62d ov5642: add i2c address change feature
* 73924ed0 ov5640_mipi: add i2c address change feature
* 12749a2 mxc_mipi_csi2: add ipu/csi info to probed output
* 9ffb829 ov5640_mipi: change registered name from ov5640 to ov5640_mipi to reduce confusion
* 98963d0 i.MX6: v4lout: none of our displays support color-space conversion
* f657dc3 dma-mapping: increase DEFAULT_DMA_COHERENT_POOL_SIZE ifdef CONFIG_VIDEO_TW68
* 41feae5 PCI: Add quirk for setting valid class for TW6869 frame grabber
* d69533a mxc_hdmi: Add only_cea parameter to mxc_hdmi module
* 5969e2c rfkill-regulator: add dt support
* 66d9883 ov5640_mipi: simplify mipi clock wait loop
* 04abce7 mxc_hdmi: enable overflow interrupt after initialization complete
* de5231f mxc_hdmi: default to keep-alive (don't detect disconnect)
* 51394b5 Add support for DVI monitors
* 4898869 ov5640_mipi: print message on gpio request failure
* e2954c5 mxc_v4l2_capture: add ipu_id to sensor_data
* af79b8b ov5640_mipi: add remove *2 and add error checking to OV5640_get_sysclk
* a03ab41 ov5640_mipi: add imx6 mipi/parallel selection
* 4f704da ov5640: add pwm option for mclk
* 81cf941 ov5642: add imx6 mipi/parallel selection
* ede1722 fix camera power down
* 6c4f140 add ar1021 touchscreen
* bc387b6 mxc_v4l2_capture: fix VIDIOC_ENUMSTD, return -EINVAL if index > 0
* 89a914b mxc_ipuv3_fb: unblank displays at init
* a1b1b16 ARM: imx: adjust vring location to be at 256MB boundary
* 8227a8a arm: dts: imx7: decrease DMA CMA to 128MB
* 4af562c ARM: imx7d: clk: add 240MHz sys main clock to init_on
* 1f43d37 usb: chipidea: Use extcon framework for ID and VBUS detection
* 24bd9a5 arm: dts: imx7: Add support for PWM polarity control
* e32dd66 pwm: imx: Add support for polarity control
* 10a6f7d cpufreq: imx7: don't support OPP table from platform data
* 46c52bd video: fbdev: mxsfb: honor native-mode
* b03cdd9 video: mxsfb: simplify parsing
* f3d8abf Revert "sgtl5000.c: HACK, defer probe when I2C not yet running"
* 967986f touchscreen: fusion_F0710A: Reset controller if clear interrupt operation fails
* d4afe65 input: touchscreen: fusion: implement multitouch with slot handling
* 5be4f48 input: touchscreen: fusion: use level triggered interrupt
* fbfa23b input: touchscreen: fusion: add device tree integration
* 02411ee input: touchscreen: fusion: platform independent GPIO description
* fd92393 input: touchscreen: fusion: fix error handling
* 808f8b9 input: touchscreen: fusion: use new I2C PM functions
* ef32550 input: touchscreen: added platform data for Fusion touchscreen
* 3e2c068 input: touchscreen: fix race condition in Fusion driver
* ac9343d input: touchscreen: add ABS_X/ABS_Y axis for Fusion touchscreen
* a9fc7d5 input: touchscreen: add Fusion 7 and 10 multi-touch driver
* e2d1fdb fbcon: logo: allow easy integration of a custom Linux boot logo
* 49f0b58 spi: spidev: invent a new hw device to work around spidev warning
* bcdfec9 ARM: imx: fix clock for i.MX 7 when Cortex-M4 is running
* 8693a14 pinctrl: pinctrl-imx: add support for LPSR GPR padctrl
* ea2ea01 mfd: rn5t618: register restart handler
* a7b0e5f mfd: add Ricoh RN5T567 PMIC suppport
* 675e67c drivers/dma/Kconfig: allow MXS_DMA for i.MX 7
* d68621a regulator: rn5t618: allow GPIO 0 to be used for an enable signal
* f0e41d7 ENGR00305648-1 ASoC: imx-sgtl5000: Support non-ssi cpu-dai
* f992a95 video: fbdev: mxsfb: fix pixelclock polarity
* d46df08 mach-imx7d.c: use enet_out clk to decide on PHY clock
* 68bf174 Input: ad7879 - add device tree support
* 63339e0 Input: ad7879 - fix default x/y axis assignment
* d1a439e Input: ad7879 - move header to platform_data directory
* 0adde3f ARM: imx: enet1: output reference clock
* 633a4e1 video: mxsfb: add compile dependencies
* f4c63ec chipidea: make usb charger optional
* c8b53a4 regulator: rn5t618: Add RN5T567 PMIC support

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
(cherry picked from commit 85b9830c91310f8e10b0ec68c76efdd69739f03b)